services:
  budget_backend:
    container_name: budget_backend
    ports:
      - 9090:9090
    build:
      context: .
    volumes: 
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports: 
      - '5432:5432'
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgresDB:
