services:

  db:
    image: postgres:16-alpine
    container_name: budget_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=budgetmannager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    container_name: budget_application
    depends_on:
      - db
    ports:
      - "9090:9090"
    command: [ "./cmd/main" ]

volumes:
  postgres_data:
